### ISSUE TITLE
Not woking with rails4

### ISSUE THREAD

**Issue by manoj2411** [resque/resque#1077]
Here are the steps i followed

I placed this line in my Gemfile: 

````
gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"
````

Created a worker:
````
class FbFriendsFetcher
  @queue = :fb_friends

  def self.perform( _user_id)
    _user = User.find( _user_id)
    _user.update_friends_list
  end
end
````

Queuing this by: 
````
Resque.enqueue( FbFriendsFetcher, _user.id)
````

Starting worker by:
````
QUEUE=fb_friends rake resque:work
````

Getting error on console:
````
NoMethodError (undefined method `client' for nil:NilClass):
  /Users/manoj/.rvm/gems/ruby-2.0.0-p247@bollyflix.com/bundler/gems/resque-dcaa6ca21b25/lib/resque/config.rb:22:in `redis_id'
  /Users/manoj/.rvm/gems/ruby-2.0.0-p247@bollyflix.com/bundler/gems/resque-dcaa6ca21b25/lib/resque.rb:93:in `redis_id'
  /Users/manoj/.rvm/gems/ruby-2.0.0-p247@bollyflix.com/bundler/gems/resque-dcaa6ca21b25/lib/resque.rb:130:in `to_s'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:117:in `set_pretty_method_name'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:34:in `initialize'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:10:in `new'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:10:in `block in from_exception'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:6:in `map'
  better_errors (0.9.0) lib/better_errors/stack_frame.rb:6:in `from_exception'
  better_errors (0.9.0) lib/better_errors/error_page.rb:52:in `backtrace_frames'
  better_errors (0.9.0) lib/better_errors/middleware.rb:114:in `log_exception'
  better_errors (0.9.0) lib/better_errors/middleware.rb:87:in `rescue in protected_app_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (0.9.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `block in call'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.0) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.0) lib/rails/rack/logger.rb:21:in `call'
  quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
  actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call'
  railties (4.0.0) lib/rails/engine.rb:511:in `call'
  railties (4.0.0) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `catch'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.2) lib/rack/server.rb:264:in `start'
  railties (4.0.0) lib/rails/commands/server.rb:84:in `start'
  railties (4.0.0) lib/rails/commands.rb:78:in `block in <top (required)>'
  railties (4.0.0) lib/rails/commands.rb:73:in `tap'
  railties (4.0.0) lib/rails/commands.rb:73:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'
````

**Comment by steveklabnik** [comment]
Resque 2.0 is now cancelled, so this is not an issue on it. #932 is a duplicate.
