### ISSUE TITLE
LoadError: No such file to load -- application_controller

### ISSUE THREAD

**Issue by itsmechlark** [resque/resque#1235]
```
** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Execute resque:setup
** Execute resque:preload
rake aborted!
LoadError: No such file to load -- application_controller
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:443:in `load'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:443:in `block in load_file'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:633:in `new_constants_in'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:442:in `load_file'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:342:in `require_or_load'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:307:in `depend_on'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:225:in `require_dependency'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/engine.rb:467:in `each'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/engine.rb:467:in `block in eager_load!'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/engine.rb:465:in `each'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/railties-4.1.4/lib/rails/engine.rb:465:in `eager_load!'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/resque-1.25.2/lib/resque/tasks.rb:61:in `block (2 levels) in <top (required)>'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/itsmechlark/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/itsmechlark/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/bin/rake:23:in `load'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/bin/rake:23:in `<main>'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/itsmechlark/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

<b>lib/tasks/resque.rb</b>

```
require 'resque/tasks'
```

gem 'resque', '>= 1.25.2'
gem 'rails', '4.1.4'

**Comment by tomlobato** [comment]
+1 the fix worked for me

**Comment by worldofchris** [comment]
+1 Thanks @itsmechlark worked for me too.

**Comment by Dark667** [comment]
bundle exec rake db:migrate --trace
rake aborted!
no such file to load -- tasks/rails
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in `gem_original_require'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in `require'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in `require'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:596:in `new_constants_in'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:225:in `load_dependency'
/home/ali/.rvm/gems/ruby-1.8.7-head/gems/activesupport-3.0.5/lib/active_support/dependencies.rb:239:in `require'
/home/ali/nes_escolares/branches/nes_escolares_dev/Rakefile:12
what ?
