### ISSUE TITLE
SocketError: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by nextofsearch** [resque/resque#1520]
Hi,

I got the following error when resque-scheduler queued a job into resque.

`rake aborted!
SocketError: getaddrinfo: Name or service not known
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in`getaddrinfo'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in `connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:295:in`connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:336:in `establish_connection'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:101:in`block in connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:293:in `with_reconnect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:100:in`connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:364:in `ensure_connected'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:221:in`block in process'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:220:in`process'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:120:in `call'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2394:in`block in _eval'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:58:in`synchronize'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2393:in `_eval'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2445:in`evalsha'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in`method_missing'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/lock/resilient.rb:17:in `locked?'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/locking.rb:66:in`master?'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:54:in `block in run'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:53:in`loop'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:53:in `run'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/cli.rb:117:in`run_forever'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <top (required)>'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in`kernel_load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in`exec'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in`dispatch'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in`start'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in`with_friendly_errors'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/bundle:23:in`load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/bundle:23:in `<main>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/ruby_executable_hooks:15:in`eval'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => resque:scheduler
(See full trace by running task with --trace)`

This error somehow stopped the entire resque worker system while resque workers (process) are listed as available workers in web-ui and I can see them when I type 'ps -ef |grep resque' but they did not process any jobs in queues. I had to restart the workers and everything went back to normal.

Not sure it is related to the fact that I upgraded resque from 1.25.2 to 1.26.0 and redis from 3.0.7 to 3.3.1 recently.

Can you please advise?

**Comment by nextofsearch** [comment]
I will use another issue #1521 instead of this.
