### ISSUE TITLE
Workers hung after a redis connection is interrupted.

### ISSUE THREAD

**Issue by nextofsearch** [resque/resque#1521]
Hi,

When a redis connection is interrupted (due to some weird name server error, which our service provider is investigating but hasn't gone away for a few days), resque workers hung while all instances using unicorn and sidekiq work just fine.

If you look at the log below, you can see: 
- resque-scheduler queued a job
- then a worker failed to process a job due to 'SocketError'
- 12 mins later somehow it tries to recover. I can see that because of sending ping/pong to redis (whenever a redis connection is opened)
- All 8 workers (including redis-scheduler) went back but did NOT process any jobs in the queue. They hung. We had to restart workers.

ruby 1.9.3 / Rails 3.1.12 / redis 3.3.1 / resque 1.26.0
I just downgraded redis from 3.3.1 to 3.2.2 after reading an [issue](https://github.com/resque/resque/issues/1452) and will see how it affects.

Does anyone know how resque recovers when the connection is interrupted?

I will appreciate any help.

Best,

```
resque-scheduler: [INFO] 2016-10-29T22:30:00+00:00: queueing CampaignArchiveWorker (do_campaign_archive_worker)
rake aborted!
SocketError: getaddrinfo: Name or service not known
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in`getaddrinfo'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:212:in `connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/connection/ruby.rb:295:in`connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:336:in `establish_connection'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:101:in`block in connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:293:in `with_reconnect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:100:in`connect'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:364:in `ensure_connected'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:221:in`block in process'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:306:in `logging'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:220:in`process'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis/client.rb:120:in `call'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2394:in`block in _eval'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:58:in `block in synchronize'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:58:in`synchronize'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2393:in `_eval'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-3.3.1/lib/redis.rb:2445:in`evalsha'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:393:in `call_with_namespace'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/redis-namespace-1.5.2/lib/redis/namespace.rb:290:in`method_missing'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/lock/resilient.rb:9:in `acquire!'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/locking.rb:66:in`master?'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:54:in `block in run'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:53:in`loop'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler.rb:53:in `run'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/cli.rb:117:in`run_forever'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/resque-scheduler-4.1.0/lib/resque/scheduler/tasks.rb:18:in `block (2 levels) in <top (required)>'
/home/deployer/apps/worker-rails3/shared/bundle/ruby/1.9.1/gems/rake-11.2.2/exe/rake:27:in`<top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in `load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:74:in`kernel_load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli/exec.rb:27:in `run'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:332:in`exec'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in`invoke_command'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:20:in`dispatch'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/cli.rb:11:in`start'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/exe/bundle:34:in `block in <top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/lib/bundler/friendly_errors.rb:100:in`with_friendly_errors'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/gems/bundler-1.13.5/exe/bundle:26:in `<top (required)>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/bundle:23:in`load'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/bundle:23:in `<main>'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/ruby_executable_hooks:15:in`eval'
/home/deployer/.rvm/gems/ruby-1.9.3-p551@rails3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => resque:scheduler
(See full trace by running task with --trace)

I, [2016-10-29T22:40:22.058066 #7104]  INFO -- : RedisUtil.ping -> PONG

resque-scheduler: [INFO] 2016-10-29T22:40:22+00:00: Starting
resque-scheduler: [INFO] 2016-10-29T22:40:22+00:00: Loading Schedule
resque-scheduler: [INFO] 2016-10-29T22:40:22+00:00: Scheduling do_campaign_instance_worker
resque-scheduler: [INFO] 2016-10-29T22:40:23+00:00: Scheduling do_daily_counter_checker
resque-scheduler: [INFO] 2016-10-29T22:40:23+00:00: Scheduling do_campaign_archive_worker
resque-scheduler: [INFO] 2016-10-29T22:40:23+00:00: Scheduling do_daily_segment_total_user_counter_worker
resque-scheduler: [INFO] 2016-10-29T22:40:24+00:00: Scheduling do_daily_counter
resque-scheduler: [INFO] 2016-10-29T22:40:24+00:00: Scheduling do_daily_core_segment_counter_worker
resque-scheduler: [INFO] 2016-10-29T22:40:24+00:00: Scheduling do_failed_purchase_recovery
resque-scheduler: [INFO] 2016-10-29T22:40:24+00:00: Scheduling do_daily_demo_account_data_worker
resque-scheduler: [INFO] 2016-10-29T22:40:24+00:00: Schedules Loaded

I, [2016-10-29T22:41:27.432944 #7868]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:41:39.167881 #8345]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:41:50.202037 #8642]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:42:01.911192 #9059]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:42:13.498346 #9368]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:42:24.236525 #9810]  INFO -- : RedisUtil.ping -> PONG
I, [2016-10-29T22:42:35.504402 #10145]  INFO -- : RedisUtil.ping -> PONG
```

**Comment by nextofsearch** [comment]
I tried resque 1.25.2, which makes no difference.

**Comment by nextofsearch** [comment]
I am using redis 3.2.2 with resqu 1.25.2 and the issue still remains.

**Comment by yoniamir** [comment]
Confirming this issue occurrs on redis 3.3.3 and resque 1.27.4.

**Comment by nickborromeo** [comment]
@nextofsearch @yoniamir It seems I also have this issue using redis `3.3.5` and resque `1.27.4` on heroku. Have any of you gotten any progress on this?

**Comment by yoniamir** [comment]
@nickborromeo This did the trick for me-
https://github.com/iloveitaly/resque-heroku-signals

**Comment by yoniamir** [comment]
@Jeremy this issue still remains in Resque..
