### ISSUE TITLE
blind passthrough has been deprecated and will be removed in redis-namespace 2.0

### ISSUE THREAD

**Issue by jaredbeck** [resque/resque#1539]
1.27.1 prints a deprecation warning every 60s. 

```
Passing 'time' command to redis as is; 
blind passthrough has been deprecated and will be removed in redis-namespace 2.0 
(at /Users/redacted/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.1/lib/resque/data_store.rb:94:in `server_time')
```

Perhaps caused by 47bce253ebc23df

Gem versions:

```
ggrep redis Gemfile.lock 
    redis (3.3.3)
    redis-actionpack (5.0.1)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 1.4.0)
    redis-activesupport (5.0.1)
      redis-store (~> 1.2.0)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (2.0.0)
      redis-store (~> 1.2.0)
    redis-rails (5.0.1)
      redis-actionpack (~> 5.0.0)
      redis-activesupport (~> 5.0.0)
      redis-store (~> 1.2.0)
    redis-store (1.2.0)
      redis (>= 2.2)
      redis-namespace (~> 1.3)
      redis (~> 3.3)
  redis-rails
```

**Comment by chrisccerami** [comment]
Thanks, this was also noted in #1538 but it's probably good to have an issue for it. I'll be looking into it now.

**Comment by chrisccerami** [comment]
It seems like we'll just need to cut a new version of `redis-namespace`, as this fix was already merged into master there.

**Comment by chrisccerami** [comment]
`redis-namespace` 1.5.3 has been released. If you upgrade you should see the deprecations go away.

**Comment by jaredbeck** [comment]
Thanks Chris. I'm no longer seeing the warning about `time`. There are still other warnings about `script` and `info`:

```
14:34:41 scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.1/lib/resque/data_store.rb:59:in `method_missing')
14:34:41 scheduler.1 | Passing 'script' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.1/lib/resque/data_store.rb:59:in `method_missing')
```

They don't repeat every 60s like the `time` warning did, though :)

**Comment by jaredbeck** [comment]
Also, judging by my log, those warnings might be coming from `resque-scheduler`.

**Comment by jaredbeck** [comment]
@chrisccerami For the 'info' and 'script' issue, should I open a new issue here or on `resque-scheduler`? Thanks.

**Comment by chrisccerami** [comment]
I would put them in `resque-scheduler` if that's where the deprecated callers are. Thanks.

**Comment by jaredbeck** [comment]
> I would put them in resque-scheduler if that's where the deprecated callers are. Thanks.

I don't know where the caller is. The call stack says `resque-1.27.2/lib/resque/data_store.rb:60`, but the originating process is `scheduler.1`.

```
13:07:00 scheduler.1 | Passing 'info' command to redis as is; administrative commands cannot be effectively namespaced and should be called on the redis connection directly; passthrough has been deprecated and will be removed in redis-namespace 2.0 (at /Users/jared/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/resque-1.27.2/lib/resque/data_store.rb:60:in `method_missing')
```

Does resque use `info` and/or `script`?

**Comment by chrisccerami** [comment]
Scheduler uses them.

**Comment by jaredbeck** [comment]
> Scheduler uses them.

Thanks Chris, I'll let them know.
