### ISSUE TITLE
Resque 1.27.2 broke Resque.inline.

### ISSUE THREAD

**Issue by hodgestar** [resque/resque#1544]
It looks like a change between 1.27.1 and 1.27.2 caused `Resque.redis = "redis://..."` to start connecting to redis even when `Resque.inline = true`.

Was this expected? If so, is there a good way to avoiding connecting to redis when in inline mode?

We're using inline mode in our test suite.

**Comment by chrisccerami** [comment]
That definitely doesn't sound intentional. I'll try to look into it today.

**Comment by chrisccerami** [comment]
I think I know what the issue is here, but I haven't had the time to test it yet. I think the problem is caused by `DataStore` now trying to call `redis.time` at initialize time in order to check if it has that command available. I'm not 100% sure yet, but I'd bet this is where it's mistakenly trying to connect to Redis even when inline. Do you have any more information about this issue, @hodgestar? Maybe the output of a test failure or an error with a stacktrace?

**Comment by hodgestar** [comment]
Partial traceback during test run with `Resque.inline = true`:
```
expected ReceiverError with "redis is pining for the fjords", got #<SocketError: getaddrinfo: Name or service not known> with backtrace:
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `getaddrinfo'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/connection/ruby.rb:229:in `connect'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/connection/ruby.rb:313:in `connect'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:336:in `establish_connection'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:101:in `block in connect'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:364:in `ensure_connected'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:221:in `block in process'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:306:in `logging'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:220:in `process'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis/client.rb:120:in `call'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis.rb:351:in `block in time'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-3.3.3/lib/redis.rb:350:in `time'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:435:in `call_with_namespace'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/redis-namespace-1.5.3/lib/redis/namespace.rb:321:in `method_missing'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/resque-1.27.2/lib/resque/data_store.rb:100:in `redis_time_available?'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/resque-1.27.2/lib/resque/data_store.rb:15:in `initialize'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/resque-1.27.2/lib/resque.rb:125:in `new'
         # /home/simon/.rvm/gems/ruby-2.3.1@pdg-data-receiver/gems/resque-1.27.2/lib/resque.rb:125:in `redis='
```

**Comment by chrisccerami** [comment]
Thanks very much! This confirmed my above suspicions. I'll try to get a fix released today.

**Comment by hodgestar** [comment]
Thank you!

**Comment by chrisccerami** [comment]
@hodgestar if you're able, would you mind pointing your Gemfile at [this](https://github.com/resque/resque/pull/1545) and seeing if it resolves your issue?

**Comment by hodgestar** [comment]
Left one question in the PR, but looks good to me. I can test on Monday.

**Comment by hodgestar** [comment]
Configuring that the PR fixes things for me (i.e. my tests pass and Redis is no longer accessed when `inline` is `true`).

**Comment by hodgestar** [comment]
Any chance this can be landed and get released?

**Comment by wjessop** [comment]
I'd be interested in a release too, would love to be able to upgrade our app.

**Comment by chrisccerami** [comment]
1.27.3 has now been released which should fix this issue. Feel free to reopen this issue if you still have problems.

**Comment by wjessop** [comment]
Thanks @chrisccerami! 🎉
