### ISSUE TITLE
Input/output error @ io_write - <STDERR>

### ISSUE THREAD

**Issue by sanjay-btc** [resque/resque#1639]
Error
Input/output error @ io_write - <STDERR>
/usr/lib64/ruby/2.3.0/logger.rb:660:in `write'
/usr/lib64/ruby/2.3.0/logger.rb:660:in `warn'
/usr/lib64/ruby/2.3.0/logger.rb:660:in `rescue in write'
/usr/lib64/ruby/2.3.0/logger.rb:644:in `write'
/usr/lib64/ruby/2.3.0/logger.rb:433:in `add'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/logger.rb:87:in `add'
/usr/lib64/ruby/2.3.0/logger.rb:507:in `error'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/log_subscriber.rb:86:in `rescue in finish'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/log_subscriber.rb:83:in `finish'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/fanout.rb:102:in `finish'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/fanout.rb:46:in `block in finish'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/fanout.rb:46:in `each'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/fanout.rb:46:in `finish'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:42:in `finish_with_state'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:27:in `instrument'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `instrument'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/logging.rb:44:in `block in tag_logger'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:26:in `tagged'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/tagged_logging.rb:69:in `tagged'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/logging.rb:44:in `tag_logger'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/execution.rb:33:in `perform_now'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/execution.rb:22:in `block in execute'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:68:in `block in wrap'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/execution_wrapper.rb:85:in `wrap'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/reloader.rb:67:in `wrap'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `instance_exec'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activesupport-5.1.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/execution.rb:20:in `execute'
/data/feed_champion/shared/bundled_gems/ruby/2.3.0/gems/activejob-5.1.3/lib/active_job/queue_adapters/resque_adapter.rb:45:in `perform'

**Comment by why-el** [comment]
Make sure your workers have access to $stderr, looks like you might have orphaned workers who lost access to that file descriptor (perhaps because of a restart).
