### ISSUE TITLE
Jobs periodically fail with `undefined method `[]' for nil:NilClass`

### ISSUE THREAD

**Issue by CodingAnarchy** [resque/resque#1677]
Doesn't seem to matter what the jobs content is, and this happens just occasionally:

```
undefined method `[]' for nil:NilClass
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:391:in `active_connection?'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:36:in `enable_query_cache!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `block in run'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `each'
/srv/app/shared/bundle/ruby/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:30:in `run'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:27:in `before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:110:in `run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:72:in `block in run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `tap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `run!'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/reloader.rb:72:in `wrap'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `instance_exec'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:136:in `run_callbacks'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/execution.rb:22:in `execute'
/srv/app/shared/bundle/ruby/2.5.0/gems/activejob-5.2.2/lib/active_job/queue_adapters/resque_adapter.rb:47:in `perform'
```

It looks like it is failing in ActiveRecord when trying to get the active connection, but I don't know what might be causing that value to be `nil` (it should be initialized to a `Concurrent::Map` by the constructor of the class in question).

Retrying the job also seems to work.

Rails: 5.2.2
Resque: 1.27.4

**Comment by rkenzhebekov** [comment]
Same for me. Getting same error with frequency of 5-8 times per day. 

ruby 2.6.6p146
rails-6.0.3.1
resque-1.27.4

**Comment by rkenzhebekov** [comment]
Hello @CodingAnarchy,

Have you ever solved issue? Have you tried to upgrade resque gem?

**Comment by CodingAnarchy** [comment]
@rkenzhebekov Unfortunately, I changed jobs about a year ago and my new employer uses Sidekiq instead of Resque, so I haven’t been tracking this any. It was still an issue then, but that’s the most up to date information I can provide.

**Comment by rkenzhebekov** [comment]
got it. Thanks @CodingAnarchy.

**Comment by gsaks123** [comment]
I've also started getting these errors, very intermittently.  Our Resque workers handle I'm guessing 10,000 jobs per day, and we're getting this exception maybe once every other day.

For a couple years we were running:
- Resque 2.0
- Ruby 2.4.4
- Rails 5.1
... and never had one of these errors. 

But then recently we upgraded a bunch of things. Resque version remains 2.0, but:
- Ruby to 2.7.3
- Rails to 5.2.6
Along with a whole slew of other gems that were updated, such as New Relic and Airbrake which do some instrumentation of Resque. So it's not possible to isolate what triggered this new exception, but I imagine the most likely candidates are either the Ruby or Rails version.

The jobs can always be retried and then complete successfully.

**Comment by chriscz** [comment]
Unsure if this still happens in Rails 6, but in Rails 5.2 it looks like I've managed to fix it with the following in the `after_fork` handler. 

The reason this seems to occur is that `discard!` was called on the connection pool in the parent process (possibly because all of the connections were discarded), but these pools are never removed from the `connection_handler` in the child process, then inside the forked worker process, when the handler looks for a connection it iterates over all the pools, but the discarded pool's behaviour is undefined as discard sets many of its instance variables to nil, resulting in the error you see in this thread.

Therefore in the forked process I discard all the pools and re-initialize the connection handler, and so far seems to work fine.

```ruby
namespace :resque do
  task :setup => :environment do
    Resque.before_first_fork do
      Rails.application.eager_load!
      ActiveRecord::Base.clear_all_connections!
    end

    Resque.after_fork do
      raise "Resque.after_fork code needs to be upgraded" if Rails::VERSION::MAJOR > 5
  
      pids = ActiveRecord::Base.connection_handler.instance_variable_get(:@owner_to_pool)
  
      # Discard all the pools (as taken from activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb
      pids.each do |pid, pools|
        pools.values.compact.each(&:discard!)
      end
  
      # Re-initialize the connection pools
      ActiveRecord::Base.connection_handler.send(:initialize)
     
      ActiveRecord::Base.establish_connection
    end
  end
end
```
