### ISSUE TITLE
Admin console tries to accessRedis::Future

### ISSUE THREAD

**Issue by arthurwozniak** [resque/resque#1697]
Hi,
I started to have issues using resque web interface in rails 6 app. Time to time when accessing web interface page I get error `Internal Server Error`. In the same time, there is error logged in systemd app service. It is quite the same all the time

```
Dec 09 13:26:12 xxx c2e_backend_puma[28464]: 2019-12-09 13:26:12 - NoMethodError - undefined method `eql?' for <Redis::Future [:type, "resque:timestamps:{"]>:Redis::Future:
Dec 09 13:26:12 xxx c2e_backend_puma[28464]: /home/khanus/.rvm/gems/ruby-2.6.3/gems/resque-2.0.0/lib/resque/server/views/stats.erb:5:in `__tilt_69873913609620'
```

```
Dec 09 13:26:13 xxx c2e_backend_puma[28464]: 2019-12-09 13:26:13 - NoMethodError - undefined method `>' for []:Array:
Dec 09 13:26:13 xxx c2e_backend_puma[28464]: /home/khanus/.rvm/gems/ruby-2.6.3/gems/resque-2.0.0/lib/resque/server/helpers.rb:58:in `page_entries_info'
```

```
Dec 09 14:00:41 xxx c2e_backend_puma[28464]: 2019-12-09 14:00:41 - NoMethodError - undefined method `[]' for <Redis::Future [:info]>:Redis::Future:
Dec 09 14:00:41 xxx c2e_backend_puma[28464]: /home/khanus/.rvm/gems/ruby-2.6.3/gems/resque-scheduler-4.4.0/lib/resque/scheduler/locking.rb:100:in `redis_master_version'
```

Here is snippet of my Gemfile.lock

```
    redis (4.1.3)
    redis-namespace (1.6.0)
      redis (>= 3.0.4)
    resque (2.0.0)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.6)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    resque-retry (1.7.3)
      resque (>= 1.25, < 3.0)
      resque-scheduler (~> 4.0)
    resque-scheduler (4.4.0)
      mono_logger (~> 1.0)
      redis (>= 3.3)
      resque (>= 1.26)
      rufus-scheduler (~> 3.2)
```

It seems that `erb` templates are receiving unresolved redis calls. Is there any way how to fix this?

**Comment by jiikko** [comment]
> NoMethodError - undefined method `eql?' for <Redis::Future [:type, "resque:timestamps:{"]>:Redis::Future:

https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/server/views/stats.erb#L1-L5

👇is my enviroment. no reproduce.

```
[8] pry(main)> Resque.info[:servers]
=> ["<Redis::Namespace v1.6.0 with client v4.1.2 for redis://localhost:6379/0/resque>"]
[9] pry(main)> Rails.version
=> "6.0.0"
[10] pry(main)> %w( resque redis keys ).map { |subtab| Resque.redis.type(subtab) }
=> ["none", "none", "none"]
```

where does you `#type` define at?

```
# reference
[26] pry(main)> Resque.redis.type
ArgumentError: wrong number of arguments (given 0, expected 1)
from /Users/koji/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/redis-namespace-1.6.0/lib/redis/namespace.rb:267:in `type'
```
