### ISSUE TITLE
NOAUTH Authentication required when forked

### ISSUE THREAD

**Issue by alxx** [resque/resque#1722]
I know that there have been some similar (fixed) issues about forked clients reconnecting and so on, but that was before Redis introduced ACL. Now the problem isn't necessarily the connection, but the authentication.

```
> r=Redis.new
 => #<Redis client v4.1.3 for redis://127.0.0.1:6379/0> 
> r.auth 'not_my_actual_password'
 => "OK" 
> r.client(:list)
 => [{"id"=>"244"...] 
> fork { puts r.client(:list) }
 => 21693 
Traceback (most recent call last):
	...
	 1: from /Users/alxx/.rvm/gems/ruby-2.5.5/gems/redis-4.1.3/lib/redis.rb:222:in `block in client'
/Users/alxx/.rvm/gems/ruby-2.5.5/gems/redis-4.1.3/lib/redis/client.rb:126:in `call': NOAUTH Authentication required. (Redis::CommandError)
```

If I `rescue` this exception, then `auth`enticate and `retry`, it works well. But isn't there some built-in mechanism to fix this problem?

**Comment by alxx** [comment]
Sorry, meant to leave this on the redis project, not resque :)
