### ISSUE TITLE
NameError: uninitialized constant Rails::Railtie

### ISSUE THREAD

**Issue by ineluki00** [resque/resque#1764]
Hi, since v2.1.0, i get the following error: 

```.rb
rails aborted!
NameError: uninitialized constant Rails::Railtie
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-2.1.0/lib/resque/railtie.rb:2:in `<module:Resque>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-2.1.0/lib/resque/railtie.rb:1:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-2.1.0/lib/resque.rb:26:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-scheduler-4.4.0/lib/resque/scheduler/delaying_extensions.rb:2:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'       
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-scheduler-4.4.0/lib/resque/scheduler/extension.rb:4:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-scheduler-4.4.0/lib/resque-scheduler.rb:4:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/resque-scheduler-4.4.0/lib/resque/scheduler/tasks.rb:4:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/workspaces/rails/app/rakefile:5:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/railties-6.1.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/railties-6.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/railties-6.1.4/lib/rails/command.rb:50:in `invoke'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/railties-6.1.4/lib/rails/commands.rb:18:in `<main>'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/ineluki/.rvm/gems/ruby-3.0.1/gems/bootsnap-1.7.7/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:4:in `<main>'
```
when trying to run db:migrate for example, as resque-scheduler is requiring resque.

Tested with:
Ruby v3.0.1
Rails v6.1.4
resque v2.1.0
resque-scheduler v4.4.0

**Comment by chrisccerami** [comment]
Can you possibly provide a sample app where this error occurs? It would make debugging much easier. It would also help to provide a backtrace for that error.
