### ISSUE TITLE
Workers not terminating as expected

### ISSUE THREAD

**Issue by SaiVaishnaviTadikamalla** [resque/resque#1869]
Started bulk workers with the below command 
queues: bin/rake environment rake resque:workers COUNT=2 QUEUE=*

During termination, on receiving SIGTERM from system, queues terminated with exit code 1 and not exit code 0
rake aborted!
Interrupt:
SignalException
Error stack trace:
/Users/user_name/.rvm/gems/ruby-3.1.2/gems/resque-2.5.0/lib/resque/tasks.rb:36:in `join'
/Users/user_name/.rvm/gems/ruby-3.1.2/gems/resque-2.5.0/lib/resque/tasks.rb:36:in `block (3 levels) in <main>'
/Users/user_name/.rvm/gems/ruby-3.1.2/gems/resque-2.5.0/lib/resque/tasks.rb:36:in `each'
/Users/user_name/.rvm/gems/ruby-3.1.2/gems/resque-2.5.0/lib/resque/tasks.rb:36:in `block (2 levels) in <main>'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/user_name/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'

This issue was not happening when queues started with  single worker **resque:work**
queues: bin/rake environment rake resque:work QUEUE=*

**Comment by darkfishy** [comment]
This could be related to #1507 
Even though the README and/or Wiki doesn't address it, it seems like starting multiple workers with `resque:workers` is only supported in development.
