### ISSUE TITLE
undefined method `key?' for JSON::Ext::Generator::State

### ISSUE THREAD

**Issue by mech** [resque/resque#810]
After upgrading to Rails 3.2.12 with its JSON 1.7.7 version, I have this undefined key? method error.

Here the stack trace:

```
activesupport (3.2.12) lib/active_support/core_ext/object/try.rb:36:in `try'
activemodel (3.2.12) lib/active_model/serializers/json.rb:91:in `as_json'
activesupport (3.2.12) lib/active_support/json/encoding.rb:47:in `block in encode'
activesupport (3.2.12) lib/active_support/json/encoding.rb:77:in    `check_for_circular_references'
activesupport (3.2.12) lib/active_support/json/encoding.rb:46:in `encode'
activesupport (3.2.12) lib/active_support/json/encoding.rb:31:in `encode'
activesupport (3.2.12) lib/active_support/core_ext/object/to_json.rb:16:in `to_json'
json (1.7.7) lib/json/common.rb:223:in `generate'
json (1.7.7) lib/json/common.rb:223:in `generate'
multi_json (1.6.0) lib/multi_json/adapters/json_common.rb:10:in `dump'
multi_json (1.6.0) lib/multi_json.rb:122:in `dump'
resque (1.23.0) lib/resque/helpers.rb:25:in `encode'
resque (1.23.0) lib/resque.rb:142:in `push'
resque (1.23.0) lib/resque/job.rb:51:in `create'
resque (1.23.0) lib/resque.rb:240:in `enqueue_to'
resque (1.23.0) lib/resque.rb:221:in `enqueue'
```

**Comment by bcackerman** [comment]
@nacengineer Thanks so much!

**Comment by johnnylai** [comment]
@nacengineer thanks!

**Comment by trodrigu** [comment]
@nacengineer Dude you are awesome thanks!

**Comment by victordelacruz** [comment]
@nacengineer Ty! lol @trodrigu what are you doing here! :D

**Comment by emanoelopes** [comment]
@nacengineer thank you!!

**Comment by janklimo** [comment]
@nacengineer hero 🍻

**Comment by darkthirst** [comment]
@nacengineer Dude! Thanks :)

**Comment by Matt970** [comment]
@nacengineer thanks dude haahah
