### ISSUE TITLE
Multiple Terms on Heroku

### ISSUE THREAD

**Issue by softwaregravy** [resque/resque#893]
We were following https://github.com/defunkt/resque/pull/638 pretty closely, and implemented handling on our side in line with this: http://hone.heroku.com/resque/2012/08/21/resque-signals.html

In our rescue logic, we try to re-queue ourselves for another worker.

Here's an example failed stack trace:

```
Exception: Resque::TermException
Error: SIGTERM
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.23.0/lib/resque/worker.rb:320:in `block in unregister_signal_handlers'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `getaddrinfo'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:112:in `connect'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/connection/ruby.rb:174:in `connect'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:263:in `establish_connection'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:69:in `connect'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:282:in `ensure_connected'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:173:in `block in process'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:248:in `logging'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:172:in `process'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:147:in `call_pipelined'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:121:in `block in call_pipeline'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:235:in `with_reconnect'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis/client.rb:119:in `call_pipeline'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2020:in `block in multi'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `block in synchronize'
/usr/local/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:36:in `synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/redis-3.0.2/lib/redis.rb:2012:in `multi'
/app/vendor/bundle/ruby/1.9.1/gems/redis-namespace-1.2.1/lib/redis/namespace.rb:220:in `method_missing'
/app/vendor/bundle/ruby/1.9.1/gems/resque-loner-1.2.1/lib/resque-ext/job.rb:19:in `create_with_loner'
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.23.0/lib/resque.rb:240:in `enqueue_to'
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.23.0/lib/resque.rb:221:in `enqueue'
/app/app/workers/resque/bidtable/bid_table_by_campaign_id_executor.rb:23:in `rescue in perform'
/app/app/workers/resque/bidtable/bid_table_by_campaign_id_executor.rb:8:in `perform'
```

Seems right -- we get the term exception on shutdown. However, this is coming from our rescue block. Our perform looks like this:

``` ruby
def perform
  # clever code here
rescue Resque::TermException
  #this next line is 23
  Resque.enqueue(BidTableByCampaignIdExecutor, campaign_id)
end
```

So we catch the term exception, then we try to re-enqueue ourselves, but get another term exception right away.

Any thoughts?

I'm trying to reproduce this in a more deterministic way right now, but wanted to bring this up in case anyone knew what was going on.

Resque version 1.23.0

Procfile for worker:

```
bidtable_worker:  env TERM_CHILD=1 RESQUE_TERM_TIMEOUT=9 QUEUES=bidtable bundle exec rake resque:work 
```

Update: I've been trying to reproduce this deterministically, and I don't seem to be able to. We do get his error in production fairly often.

**Comment by jeremy** [comment]
Heroku TERM support: https://github.com/iloveitaly/resque-heroku-signals#readme
