### ISSUE TITLE
rake resque:work aborts startup if the first job raises an uninitialized constant error

### ISSUE THREAD

**Issue by ajsharp** [resque/resque#955]
AFAIK, this was something that changed from 1.23.0 to 1.24.1. I'd imagine that the intended behavior here, given resque's forking architecture, would be for the parent process to continue running, place the job into the failure queue, and move on to the next. Also, we're not using the new "dont' fork" settings added in recent versions.

**Comment by chrisccerami** [comment]
I have a solution to the `NameError` killing the parent, but I want to try to find a way to reproduce this problem first so I can ensure that it actually solves it. Is it accurate to say that the problem can be reproduced by enqueueing a job with a class that doesn't exists?

**Comment by theaxel** [comment]
Me having the same problem. Any solution for the NameError?

**Comment by chrisccerami** [comment]
Like I said, I believe I have a solution, but I would like to be able to reliably recreate the problem first.

**Comment by john007abhilash** [comment]
I am facing the same issue that the class is not found, i am using Contentful Scheduler https://github.com/contentful/contentful-scheduler.rb to publish and unpublish content and only while **unpublishing contents** i get this error **randomly**

uninitialized constant Contentful::Scheduler::Tasks::Unpublish Did you mean? Contentful::Scheduler::Tasks::Publish
/root/.gem/ruby/gems/resque-1.27.4/lib/resque.rb:96:in `block in constantize'
/root/.gem/ruby/gems/resque-1.27.4/lib/resque.rb:90:in `each'
/root/.gem/ruby/gems/resque-1.27.4/lib/resque.rb:90:in `constantize'
