### ISSUE TITLE
Resque::TermException

### ISSUE THREAD

**Issue by maletor** [resque/resque#978]
We are looking at getting Resque 1.x running smoothly on the Cedar platform with resque_mailer. I have the following in `lib/tasks/resque.rake`.

``` ruby
require "resque/tasks"

task "resque:setup" => :environment do
  Resque.before_fork do
  defined?(ActiveRecord::Base) and
    ActiveRecord::Base.connection.disconnect!
  end

  Resque.after_fork do
    defined?(ActiveRecord::Base) and
      ActiveRecord::Base.establish_connection
  end
end
```

The problem is I am still getting lots of `Resque::TermException` errors upon deploying/restarting the workers.

I should add I also have this in the `Procfile`.

```
mailerworker: env INTERVAL=0.1 QUEUE=mailer TERM_CHILD=1 RESQUE_TERM_TIMEOUT=10 bundle exec rake resque:work
```

Even still, New Relic reports the jobs take less than 4 seconds to run, so this really shouldn't be happening in the first place.

Here is an example trace, though they do not all look like this:

```
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.24.1/lib/resque/worker.rb:327:in `block in unregister_signal_handlers'
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.24.1/lib/resque/worker.rb:327:in `call'
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.24.1/lib/resque/worker.rb:327:in `new'
/app/vendor/bundle/ruby/1.9.1/gems/resque-1.24.1/lib/resque/worker.rb:327:in `block in unregister_signal_handlers'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/openssl/buffering.rb:174:in `call'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/openssl/buffering.rb:174:in `read_nonblock'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/protocol.rb:141:in `rbuf_fill'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:929:in `recv_response'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:915:in `block in getok'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:939:in `critical'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:913:in `getok'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:860:in `rcptto'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:841:in `block in rcptto_list'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:839:in `each'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:839:in `rcptto_list'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:660:in `send_message'
/app/vendor/bundle/ruby/1.9.1/gems/mail-2.5.3/lib/mail/network/delivery_methods/smtp.rb:137:in `block in deliver!'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/net/smtp.rb:520:in `start'
/app/vendor/bundle/ruby/1.9.1/gems/mail-2.5.3/lib/mail/network/delivery_methods/smtp.rb:136:in `deliver!'
/app/vendor/bundle/ruby/1.9.1/gems/mail-2.5.3/lib/mail/message.rb:2033:in `do_delivery'
/app/vendor/bundle/ruby/1.9.1/gems/mail-2.5.3/lib/mail/message.rb:229:in `block in deliver'
/app/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:415:in `block in deliver_mail'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
/app/vendor/bundle/ruby/1.9.1/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:413:in `deliver_mail'
/app/vendor/bundle/ruby/1.9.1/gems/mail-2.5.3/lib/mail/message.rb:229:in `deliver'
/app/vendor/bundle/ruby/1.9.1/gems/resque_mailer-2.2.3/lib/resque_mailer.rb:44:in `perform'
```

**Comment by jeremy** [comment]
Heroku TERM support: https://github.com/iloveitaly/resque-heroku-signals#readme
